FROM mongo:latest

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

#COPY mongo.conf /usr/local/etc/mongo/mongo.conf
#COPY ./conf/mongodb.conf /usr/local/etc/mongo/mongo.conf

VOLUME /data/db /data/configdb

#ADD ./conf/mongodb.conf /etc/mongo/mongodb.conf

#CMD ["mongod", "--bind_ip", "172.16.0.8"]

EXPOSE 27017
EXPOSE 28017

